module EntriesHelper
  def entry_date(e)
    e.created_at.strftime("%A, %B %e %Y")
  end

  def fake_entry_text
    "%-10s" % FAKE_TEXT.split(".").sample
  end

  def random_sentence_end_mark
    ("." * 20 << "!" << "?").split("").sample
  end

  def attribution_text(entry)
    if current_user && entry.user == current_user
      'you'
    elsif entry.user.present?
      entry.user.display_name
    else
      'Anonymous'
    end
  end

  FAKE_TEXT =
<<-EULA
  END-USER LICENSE AGREEMENT FOR MICROSOFT SOFTWARE

  MICROSOFT WINDOWS INSTALLER VERSION 31

  IMPORTANT—READ CAREFULLY: This End-User License Agreement (“EULA”) is a legal agreement between you (either an individual or a single entity) and Microsoft Corporation (“Microsoft”) for the Microsoft software that accompanies this EULA, which includes computer software and may include associated media, printed materials, “online” or electronic documentation, and Internet-based services (“Software”).  An amendment or addendum to this EULA may accompany the Software.  YOU AGREE TO BE BOUND BY THE TERMS OF THIS EULA BY INSTALLING, COPYING, OR OTHERWISE USING THE SOFTWARE. IF YOU DO NOT AGREE, DO NOT INSTALL, COPY, OR USE THE SOFTWARE; YOU MAY RETURN IT TO YOUR PLACE OF PURCHASE (IF APPLICABLE) FOR A FULL REFUND.

  1	GRANT OF LICENSE.  Microsoft grants you the following rights provided that you comply with all terms and conditions of this EULA:  You may install and use the Software on a single computer solely for the purpose of designing, developing, and testing applications for use with Microsoft Windows 2000 Service Pack 3, Windows 2000 Service Pack 4, Windows XP, Windows XP Service Pack 1, Windows Server 2003 and Windows XP Service Pack 2.  You may not use the Software to create files which are not compatible with the Microsoft Windows Installer file format. 
  11	Documentation.  You may make and use an unlimited number of copies of any documentation, provided that such copies shall be used only for personal purposes and are not to be republished or distributed (either in hard copy or electronic form) beyond your premises.
  12	Storage/Network Use. You may also store or install a copy of the Software on a storage device, such as a network server, used only to install or run the Software on computers used by a licensed end user in accordance with Section 11.  A single license for the Software may not be shared or used concurrently by multiple end users.
  2	ADDITIONAL LICENSE RIGHTS -- REDISTRIBUTABLE CODE.  In addition to the rights granted in Section 1, certain portions of the Software, as described in this Section 2, are provided to you with additional license rights.  These additional license rights are conditioned upon your compliance with the distribution requirements and license restrictions described in Section 3.
  21	Sample Code. Microsoft grants you the right to: (a) use and modify the source code version of those portions of the Software identified as “Samples” in REDIST.TXT or elsewhere in the Software (“Sample Code”) for the sole purposes of designing, developing, and testing your Software(s), and (b) a limited, nonexclusive, royalty-free right to reproduce and distribute the Sample Code, along with any modifications thereof, in object and/or source code form.  For applicable redistribution requirements for Sample Code, see Section 3 below.
  22	Redistributable Code. Microsoft grants you a nonexclusive, royalty-free right to reproduce and distribute the object code form of any portion of the Software listed in REDIST.TXT (“Redistributable Code”).  For general redistribution requirements for Redistributable Code, see Section 3, below.  
  3	DISTRIBUTION REQUIREMENTS AND OTHER LICENSE RIGHTS AND LIMITATIONS.  If you choose to exercise your rights under Section 2, any redistribution by you is subject to your compliance with Section 3.
  31	General Distribution Requirements.  
  (a)	If you choose to redistribute Sample Code, or Redistributable Code (collectively, the “Redistributables”) as described in Section 2, you agree:  (i) except as otherwise noted in Section 2.1 (Sample Code), to distribute the Redistributables only in object code form and in conjunction with and as a part of a software application product developed by you that adds significant and primary functionality to the Redistributables (“Licensee Software”); (ii) that the Redistributables only operate in conjunction with Microsoft Windows platforms and ) the application does not allow the use of the Redistributables for files which are not compatible with the Microsoft Windows Installer; (iii) the library code in the LIB directory may only be redistributed when linked into your application; (iv) that if the Licensee Software is distributed beyond Licensee’s premises or externally from Licensee’s organization, to distribute the Licensee Software containing the Redistributables pursuant to an end user license agreement (which may be “break-the-seal”, “click-wrap” or signed), with terms no less protective than those contained in this EULA; (v) not to use Microsoft’s name, logo, or trademarks to market the Licensee Software; (vi) to display your own valid copyright notice which shall be sufficient to protect Microsoft’s copyright in the Software; (vii) not to remove or obscure any copyright, trademark or patent notices that appear on the Software as delivered to you; (viii) to indemnify, hold harmless, and defend Microsoft from and against any claims or lawsuits, including attorney’s fees, that arise or result from the use or distribution of the Licensee Software; (ix) to otherwise comply with the terms of this EULA; and (x) agree that Microsoft reserves all rights not expressly granted.  
  You also agree not to permit further distribution of the Redistributables by your end users except you may permit further redistribution of the Redistributables by your distributors to your end-user customers if your distributors only distribute the Redistributables in conjunction with, and as part of, the Licensee Software, you comply with all other terms of this EULA, and your distributors comply with all restrictions of this EULA that are applicable to you. 
  (b)	If you use the Redistributables, then in addition to your compliance with the applicable distribution requirements described for the Redistributables, the following also applies.  Your license rights to the Redistributables are conditioned upon your not (i) creating derivative works of the Redistributables in any manner that would cause the Redistributables in whole or in part to become subject to any of the terms of an Excluded License; or (ii) distributing the Redistributables (or derivative works thereof) in any manner that would cause the Redistributables to become subject to any of the terms of an Excluded License.  An “Excluded License” is any license that requires as a condition of use, modification and/or distribution of software subject to the Excluded License, that such software or other software combined and/or distributed with such software be (x) disclosed or distributed in source code form; (y) licensed for the purpose of making derivative works; or (z) redistributable at no charge.
  4	RESERVATION OF RIGHTS AND OWNERSHIP.  Microsoft reserves all rights not expressly granted to you in this EULA.  The Software is protected by copyright and other intellectual property laws and treaties. Microsoft or its suppliers own the title, copyright, and other intellectual property rights in the Software.  The Software is licensed, not sold.
  5	LIMITATIONS ON REVERSE ENGINEERING, DECOMPILATION, AND DISASSEMBLY.  You may not reverse engineer, decompile, or disassemble the Software, except and only to the extent that such activity is expressly permitted by applicable law notwithstanding this limitation.
  6	NO RENTAL/COMMERCIAL HOSTING. You may not rent, lease, lend or provide commercial hosting services with the Software.
  7	CONSENT TO USE OF DATA.  You agree that Microsoft and its affiliates may collect and use technical information gathered as part of the product support services provided to you, if any, related to the Software.  Microsoft may use this information solely to improve our products or to provide customized services or technologies to you and will not disclose this information in a form that personally identifies you.   
  8	LINKS TO THIRD PARTY SITES.  You may link to third party sites through the use of the Software.  The third party sites are not under the control of Microsoft, and Microsoft is not responsible for the contents of any third party sites, any links contained in third party sites, or any changes or updates to third party sites.  Microsoft is not responsible for webcasting or any other form of transmission received from any third party sites.  Microsoft is providing these links to third party sites to you only as a convenience, and the inclusion of any link does not imply an endorsement by Microsoft of the third party site.
  9	ADDITIONAL SOFTWARE/SERVICES.  This EULA applies to updates, supplements, add-on components, or Internet-based services components, of the Software that Microsoft may provide to you or make available to you after the date you obtain your initial copy of the Software, unless we provide other terms along with the update, supplement, add-on component, or Internet-based services component.  Microsoft reserves the right to discontinue any Internet-based services provided to you or made available to you through the use of the Software.  
  10	NOT FOR RESALE SOFTWARE.  Software identified as “Not For Resale” or “NFR,” may not be sold or otherwise transferred for value, or used for any purpose other than demonstration, test or evaluation.
  11	ACADEMIC EDITION SOFTWARE.  To use Software identified as “Academic Edition” or “AE,” you must be a “Qualified Educational User.”   For qualification-related questions, please contact the Microsoft Sales Information Center/One Microsoft Way/Redmond, WA 98052-6399 or the Microsoft subsidiary serving your country.
  12	EXPORT RESTRICTIONS.  You acknowledge that the Software is subject to US export jurisdiction.  You agree to comply with all applicable international and national laws that apply to the Software, including the US Export Administration Regulations, as well as end-user, end-use, and destination restrictions issued by US and other governments.   For additional information see <http://wwwmicrosoftcom/exporting/>.
  13	SOFTWARE TRANSFER.  The initial user of the Software may make a one-time permanent transfer of this EULA and Software to another end user, provided the initial user retains no copies of the Software.  This transfer must include all of the Software (including all component parts, the media and printed materials, any upgrades, this EULA, and, if applicable, the Certificate of Authenticity).  The transfer may not be an indirect transfer, such as a consignment.  Prior to the transfer, the end user receiving the Software must agree to all the EULA terms.
  14	TERMINATION.  Without prejudice to any other rights, Microsoft may terminate this EULA if you fail to comply with the terms and conditions of this EULA. In such event, you must destroy all copies of the Software and all of its component parts.
  15	DISCLAIMER OF WARRANTIES. Microsoft and its suppliers provide the Software and support services (if any) AS IS AND WITH ALL FAULTS, and hereby disclaim all other warranties and conditions, whether express, implied or statutory, including, but not limited to, any (if any) implied warranties, duties or conditions of merchantability, of fitness for a particular purpose, of reliability or availability, of accuracy or completeness of responses, of results, of workmanlike effort, of lack of viruses, and of lack of negligence, all with regard to the Software, and the provision of or failure to provide support or other services, information, software, and related content through the Software or otherwise arising out of the use of the Software.  ALSO, THERE IS NO WARRANTY OR CONDITION OF TITLE, QUIET ENJOYMENT, QUIET POSSESSION, CORRESPONDENCE TO DESCRIPTION OR NON-INFRINGEMENT WITH REGARD TO THE Software.
  16	EXCLUSION OF INCIDENTAL, CONSEQUENTIAL AND CERTAIN OTHER DAMAGES.  TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, IN NO EVENT SHALL MICROSOFT OR ITS SUPPLIERS BE LIABLE FOR ANY SPECIAL, INCIDENTAL, PUNITIVE, INDIRECT, OR CONSEQUENTIAL DAMAGES WHATSOEVER (INCLUDING, BUT NOT LIMITED TO, DAMAGES FOR LOSS OF PROFITS OR CONFIDENTIAL OR OTHER INFORMATION, FOR BUSINESS INTERRUPTION, FOR PERSONAL INJURY, FOR LOSS OF PRIVACY, FOR FAILURE TO MEET ANY DUTY INCLUDING OF GOOD FAITH OR OF REASONABLE CARE, FOR NEGLIGENCE, AND FOR ANY OTHER PECUNIARY OR OTHER LOSS WHATSOEVER) ARISING OUT OF OR IN ANY WAY RELATED TO THE USE OF OR INABILITY TO USE THE SOFTWARE, THE PROVISION OF OR FAILURE TO PROVIDE SUPPORT OR OTHER SERVICES, INFORMATION, SOFTWARE, AND RELATED CONTENT THROUGH THE SOFTWARE OR OTHERWISE ARISING OUT OF THE USE OF THE SOFTWARE, OR OTHERWISE UNDER OR IN CONNECTION WITH ANY PROVISION OF THIS EULA, EVEN IN THE EVENT OF THE FAULT, TORT (INCLUDING NEGLIGENCE), MISREPRESENTATION, STRICT LIABILITY, BREACH OF CONTRACT OR BREACH OF WARRANTY OF MICROSOFT OR ANY SUPPLIER, AND EVEN IF MICROSOFT OR ANY SUPPLIER HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. 
  17	LIMITATION OF LIABILITY AND REMEDIES. NOTWITHSTANDING ANY DAMAGES THAT YOU MIGHT INCUR FOR ANY REASON WHATSOEVER (INCLUDING, WITHOUT LIMITATION, ALL DAMAGES REFERENCED HEREIN AND ALL DIRECT OR GENERAL DAMAGES IN CONTRACT OR ANYTHING ELSE), THE ENTIRE LIABILITY OF MICROSOFT AND ANY OF ITS SUPPLIERS UNDER ANY PROVISION OF THIS EULA AND YOUR EXCLUSIVE REMEDY HEREUNDER (EXCEPT FOR ANY REMEDY OF REPAIR OR REPLACEMENT ELECTED BY MICROSOFT WITH RESPECT TO ANY BREACH OF THE LIMITED WARRANTY) SHALL BE LIMITED TO THE GREATER OF THE ACTUAL DAMAGES YOU INCUR IN REASONABLE RELIANCE ON THE Software UP TO THE AMOUNT ACTUALLY PAID BY YOU FOR THE Software OR US$500.  THE FOREGOING LIMITATIONS, EXCLUSIONS AND DISCLAIMERS (INCLUDING SECTIONS 15, 16 AND 17) SHALL APPLY TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, EVEN IF ANY REMEDY FAILS ITS ESSENTIAL PURPOSE.
  18	US GOVERNMENT LICENSE RIGHTS. All Software provided to the US Government pursuant to solicitations issued on or after December 1, 1995 is provided with the commercial license rights and restrictions described elsewhere herein.  All Software provided to the US Government pursuant to solicitations issued prior to December 1, 1995 is provided with “Restricted Rights” as provided for in FAR, 48 CFR 52.227-14 (JUNE 1987) or DFAR, 48 CFR 252.227-7013 (OCT 1988), as applicable. 
  19	APPLICABLE LAW.  If you acquired this Software in the United States, this EULA is governed by the laws of the State of Washington.  If you acquired this Software in Canada, unless expressly prohibited by local law, this EULA is governed by the laws in force in the Province of Ontario, Canada; and, in respect of any dispute which may arise hereunder, you consent to the jurisdiction of the federal and provincial courts sitting in Toronto, Ontario. If you acquired this Software in the European Union, Iceland, Norway, or Switzerland, then local law applies.  If you acquired this Software in any other country, then local law may apply. 
  20	ENTIRE AGREEMENT; SEVERABILITY.  This EULA (including any addendum or amendment to this EULA which is included with the Software) are the entire agreement between you and Microsoft relating to the Software and the support services (if any) and they supersede all prior or contemporaneous oral or written communications, proposals and representations with respect to the Software or any other subject matter covered by this EULA.  To the extent the terms of any Microsoft policies or programs for support services conflict with the terms of this EULA, the terms of this EULA shall control.  If any provision of this EULA is held to be void, invalid, unenforceable or illegal, the other provisions shall continue in full force and effect.
EULA
end
